// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTvpvFF0KyJ5gqhw_eBPgvqhpQJ4XkWFc',
    appId: '1:959464962918:web:8ee3df54a8d53bc6a2e6a7',
    messagingSenderId: '959464962918',
    projectId: 'foodstore-4c5c8',
    authDomain: 'foodstore-4c5c8.firebaseapp.com',
    storageBucket: 'foodstore-4c5c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxzNrmB62X4zRZ6eQAdzRO_lcAtflmBw',
    appId: '1:959464962918:android:f5ab94d5d7287828a2e6a7',
    messagingSenderId: '959464962918',
    projectId: 'foodstore-4c5c8',
    storageBucket: 'foodstore-4c5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOsvaLnw6VJ4moEfIXqD54Mrtzo7GoBw',
    appId: '1:959464962918:ios:319cc856b04eba15a2e6a7',
    messagingSenderId: '959464962918',
    projectId: 'foodstore-4c5c8',
    storageBucket: 'foodstore-4c5c8.appspot.com',
    iosBundleId: 'com.example.foodstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOsvaLnw6VJ4moEfIXqD54Mrtzo7GoBw',
    appId: '1:959464962918:ios:319cc856b04eba15a2e6a7',
    messagingSenderId: '959464962918',
    projectId: 'foodstore-4c5c8',
    storageBucket: 'foodstore-4c5c8.appspot.com',
    iosBundleId: 'com.example.foodstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTvpvFF0KyJ5gqhw_eBPgvqhpQJ4XkWFc',
    appId: '1:959464962918:web:2bf398bf1a1205cea2e6a7',
    messagingSenderId: '959464962918',
    projectId: 'foodstore-4c5c8',
    authDomain: 'foodstore-4c5c8.firebaseapp.com',
    storageBucket: 'foodstore-4c5c8.appspot.com',
  );
}
